### ISSUE TITLE
i can't install it

### ISSUE THREAD

**Issue by fauziardiyanto** [laraspace/laraspace#1]
when i try to php artisan key:generate, there is an error, says 
"Warning: require(C:\laragon\www\laraspace/vendor/autoload.php): failed to open stream: No such file or directory in C:\laragon\www\laraspace\artisan on line 18"

there is no folder vendor/autoload.php.

**Comment by mohitpanjwani** [comment]
You will need to run ‘composer install’ before running that command.

I will update the documentation to make it clear for everyone.

**Comment by fauziardiyanto** [comment]
i'mso sorry, my bad, i was in a rush before, i think i run a command php artisan install, thank u

**Comment by mohitpanjwani** [comment]
hehe! no worries 👍
