### ISSUE TITLE
Flash not working with laracasts/flash:^3.0

### ISSUE THREAD

**Issue by marcosrocha85** [laraspace/laraspace#16]
I had a little headache after update my composer outdated modules. In the process I updated [laracasts/flash](https://github.com/laracasts/flash) to version 3.0 and the toastr stopped showing up. I didn't realized in the very beginning taking a couple of hours to identify what I did wrong. I'd like to suggest update sources in order to work with laracasts/flash:3.0. If you guys could explain to me how laraspace works with flash I can try update myself and send a pull request.

**Comment by mohitpanjwani** [comment]
Hello marcus!

I am not aware about the changes in latest `laracasts/flash` package but you can check `laraspace-notifs.blade.php` & `laraspace-notifs.js` to see how it works. 

Basically we just get the notification message and notification-level from session variable ( which comes from the package ) and then set it on `data-attribute` of the element in laraspace-notifs.blade.php.  

And then in `laraspace-notifs.js`, we fire the notification based on the provided attributes.

**Comment by marcosrocha85** [comment]
Thank you for fast response @mohitpanjwani .

According to [release log](https://github.com/laracasts/flash/releases), version 3.0 has breaking changes from v2. Basically:
```php
// Before
flash()->success('My message');

// After
flash('My message')->success();

// Before
flash()->overlay('My message');

// After
flash('My message')->overlay();
```

I'll take a look about the working flow of laraspace-notifs and any further news I leave here.

**Comment by marcosrocha85** [comment]
I made a little change on laraspace-notifs based on breaking changes. I hope it's correct.

> **Breaking Changes From v2**
> 
> Please note that there are no breaking changes with v3, unless you published our old view templates to your project.
> 
> - We now flash a single flash_notification array to the session, and nothing else. As such, if maintaining your own views, you'll need to update them accordingly. See here: https://github.com/laracasts/flash/blob/master/src/views/message.blade.php

**Comment by mohitpanjwani** [comment]
Looks good to me! Can you add a PR for the same?
