### ISSUE TITLE
use Theme component

### ISSUE THREAD

**Issue by karneaud** [laraspace/laraspace#22]
I want to be able to use your theme as a parent theme for a theme module. Can i just extract the "resources" and/or "public" folder?

**Comment by mohitpanjwani** [comment]
@karneaud Sorry! I didn't get what you are trying to say.

Which theme module exactly are you trying to use it for? Also can you explain what problem do you have exactly?

**Comment by karneaud** [comment]
@mohitpanjwani sorry believe i have the wrong repo. Will close
