### ISSUE TITLE
No config file or laraspace artisan command

### ISSUE THREAD

**Issue by JanCusters** [laraspace/laraspace#7]
Hi,

According to the documentation one should be able to remove the demo files by running the command php artisan laraspace:clean or by configuring the laraspace config file. The config file is nowhere to be seen and running the artisan command returns this error:   There are no commands defined in the "laraspace" namespace.  

Should I remove everything by hand?

**Comment by mohitpanjwani** [comment]
Here's the config file which mentions the files and folders that will be deleted if you run `php artisan laraspace:clean` command: 

https://github.com/laraspace/laraspace/blob/master/config/laraspace.php

It looks like this: 
<img width="952" alt="screen shot 2019-02-20 at 6 41 20 pm" src="https://user-images.githubusercontent.com/8002555/53094115-46e2ef00-353f-11e9-9c59-bf1a3808b4df.png">
